name: Ubuntu 20.04 SSH (Deprecated, under maintenance)
run-name: Welcome ${{ github.actor }} to Rinne VPS 🚀
on:
  workflow_dispatch:
    inputs:
      ps5:
        description: 'Add username'
        required: false
      ps:
        description: 'User password'
        required: true
      os:
        description: 'Your SSH Public Key'
        required: true
      
jobs:
  Ubuntu_2004:
    timeout-minutes: 360
    runs-on: ubuntu-20.04
    steps:
    
    
    - name: Running...
      run: |
           sudo su runneradmin
           cd
           sudo service sshd start
           
           
           sudo useradd -m runneradmin &>/dev/null &
           sudo useradd -m ${{ github.event.inputs.ps5 }} &>/dev/null &
           echo 'runneradmin:${{ github.event.inputs.ps }}' | sudo chpasswd &>/dev/null &
           sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd &>/dev/null &
           sudo useradd -m runner &>/dev/null &
           echo 'runner:${{ github.event.inputs.ps }}' | sudo chpasswd &>/dev/null &
           echo '${{ github.event.inputs.ps5 }}:${{ github.event.inputs.ps }}' | sudo chpasswd &>/dev/null &
           sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd &>/dev/null &
           echo Username: ${{ github.event.inputs.ps5 }} , runneradmin, runner
           cd && cd && cd && cd && echo "${{ github.event.inputs.os }}"  >> /home/runneradmin/.ssh/authorized_keys
           sudo apt update &>/dev/null 
           sudo apt install snapd -y &>/dev/null 
           sudo snap install ngrok &>/dev/null 
           echo THE NGROK TOKEN IS GENERATED BY ME, YOU DO NOT NEED TO ENTER A TOKEN
           ngrok authtoken 2Q2rHTw4NtzRr7TmzWjgDtasgoF_5hJEnRDGjGMj3bYC25JoS &>/dev/null &
           ngrok authtoken 2Q2rLzdiscxRmtlgRGVUiPyrjKK_53w6FYjWtS9KJGu9Gctfu &>/dev/null &
           ngrok tcp 22 &>/dev/null &
           echo To connect via SSH through the tunnel, use the following IP address, and remove "tcp://" and the port number from the IP address
           curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Token error"
           echo With OPENSSH CLI, enter ssh USERNAME@IP -p PORT_NUMBER
           yes &>/dev/null
