name: Ubuntu 22.04
run-name: Welcome ${{ github.actor }} to Rinne VPS 🚀
on:
  workflow_dispatch:
    inputs:
      ps:
        description: 'Enter password'
        required: true
      os:
        description: 'Enter Debian Linux code for Chrome Remote Desktop'
        required: true
      os2:
        description: 'Enter PIN (6 or more digits)'
        required: true
jobs:
  Ubuntu_2204:
    timeout-minutes: 360
    runs-on: ubuntu-22.04
    steps:
    - name: Download configuration files...
      uses: actions/checkout@v1
    - name: Verifying Debian Linux code
      run: |
           echo Changing password to: PASSWORD DISPLAY REMOVED FOR SECURITY REASONS
         
           sudo useradd -m runneradmin &>/dev/null &
           echo 'runneradmin:${{ github.event.inputs.ps }}' | sudo chpasswd &>/dev/null &
           sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd &>/dev/null &
           sudo useradd -m runner &>/dev/null &
           echo 'runner:${{ github.event.inputs.ps }}' | sudo chpasswd &>/dev/null &
           sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd &>/dev/null &
           echo Username: runneradmin or runner
           echo Password: PASSWORD DISPLAY REMOVED FOR SECURITY REASONS
         
           bash bash1.sh
           ${{ github.event.inputs.os }} --pin=${{ github.event.inputs.os2 }} &>/dev/null 
    - name: Wait for this step to finish before connecting to the VPS!
      run: |
           bash bash2.sh
    - name: Success!
      run: yes &>/dev/null
      timeout-minutes: 999
